name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --release
      - name: Tests
        run: cargo test --all --verbose
      - name: Package tarball
        run: |
          chmod +x scripts/package-linux.sh || true
          scripts/package-linux.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: proto-honeypot-dist
          path: dist/*.tar.gz
